apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: system
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: argocd
    repoURL: 'https://github.com/Aste88/gitops-minikube.git'
    targetRevision: master
    helm:
      valueFiles:
        - values.yaml
  ignoreDifferences:
    - group: "*"
      namespace: argocd
      kind: Application
      jsonPointers:
        - /spec/syncPolicy/automated
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - CreateNamespace=true
      # - ApplyOutOfSyncOnly=true
      - Prune=true