apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-controller
  namespace: argocd
spec:
  project: system
  destination:
    namespace: system
    server: 'https://kubernetes.default.svc'
  source:
    path: nginx-ingress-controller
    repoURL: 'https://github.com/Aste88/gitops-minikube.git'
    targetRevision: master
    # helm:
    #   valueFiles:
    #     - values.yaml
    plugin:
      name: kustomized-helm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - Prune=true