apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helm-out.yaml

patches:
  - patch: |-
      - op: add
        path: /spec/allocateLoadBalancerNodePorts
        value: false
    target:
      kind: Service
      name: nginx-ingress-controller
