apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: argocd
spec:
  project: system
  destination:
    server: {{ .Values.spec.destination.server }}
  source:
    path: namespaces
    repoURL: 'https://github.com/Aste88/gitops-minikube.git'
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - Prune=true