apiVersion: v2
name: kube-prometheus-stack
type: application
version: 1.1.0
appVersion: 0.56.0
sources:
  - https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack
dependencies:
  - name: kube-prometheus-stack
    version: 35.0.0
    repository: https://prometheus-community.github.io/helm-charts
