apiVersion: v1
kind: PersistentVolume
metadata:
  name: cephfs-develop
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 30Ti
  csi:
    driver: cephfs.csi.ceph.com
    nodeStageSecretRef:
      # node stage secret name
      name: ceph-admin-secret
      # node stage secret namespace where above secret is created
      namespace: ceph-csi
    volumeAttributes:
      # Required options from storageclass parameters need to be added in volumeAttributes
      "clusterID": "cluster0"
      "fsName": "cephfs"
      "staticVolume": "true"
      "rootPath": /
    # volumeHandle can be anything, need not to be same
    # as PV name or volume name. keeping same for brevity
    volumeHandle: cephfs-develop
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cephfs-develop-claim
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Ti
  volumeMode: Filesystem
  volumeName: cephfs-develop
